### ISSUE TITLE
CI failure for build of sshfs-2021.8.1 on win py3.6 and win py3.9

### ISSUE THREAD

**Issue by maresb** [conda-forge/sshfs-feedstock#9]
It looks like the builders were somehow not properly initialized in these two cases:

https://github.com/conda-forge/sshfs-feedstock/runs/3532553276

Do the admins for this project have the permissions to rerun the failed jobs on Azure? I think this should be somehow doable without creating a new build.

This is currently blocking https://github.com/conda-forge/dvc-feedstock/pull/240

**Comment by efiop** [comment]
@maresb Thank you so much for investigating this! 🙏 Restarted.

**Comment by efiop** [comment]
Fixed in https://github.com/conda-forge/sshfs-feedstock/runs/3691170232 (bumped a build number, since original build had outdated tokens). Thank you! 🙏

**Comment by maresb** [comment]
Great! Glad it worked. Thanks for explaining the reason for the build number, very good to know.
